"""empty message

Revision ID: 0f7b7125f050
Revises: None
Create Date: 2016-02-29 11:19:29.108150

"""

# revision identifiers, used by Alembic.
revision = '0f7b7125f050'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base')
    ### end Alembic commands ###
