"""empty message

Revision ID: 2c24ba2494cb
Revises: daff82b28732
Create Date: 2016-03-26 20:22:50.228323

"""

# revision identifiers, used by Alembic.
revision = '2c24ba2494cb'
down_revision = 'daff82b28732'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
