"""empty message

Revision ID: d4f14d134a36
Revises: 2c24ba2494cb
Create Date: 2016-08-13 23:41:58.389486

"""

# revision identifiers, used by Alembic.
revision = 'd4f14d134a36'
down_revision = '2c24ba2494cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interested_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interested_email')
    ### end Alembic commands ###
