"""empty message

Revision ID: daff82b28732
Revises: 0f7b7125f050
Create Date: 2016-03-12 10:51:48.800310

"""

# revision identifiers, used by Alembic.
revision = 'daff82b28732'
down_revision = '0f7b7125f050'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'base_pkey')
    )
    ### end Alembic commands ###
